#!/bin/bash
set -euo pipefail

marketing_version=1.1.1
build_version=1

textBold="\e[1m\e[34m"  # Dark Blue
textNormal="\e[0m"

function full_path_of_directory() {
    local directory_name
    directory_name="$1"
    current_directory=$(pwd)
    while [[ "$(basename "$current_directory")" != "$directory_name" && ${#current_directory} -gt 1 ]]
    do
        current_directory=$(dirname "$current_directory")
    done
    if (( ${#current_directory} <= 1 ))
    then
        echo ">>> Error: Path of '$1' not found." 1>&2
        kill -9 -- $$
        exit 1
    fi
    echo "$current_directory"
}

function update_version() {
    local project="$1"
    plutil -replace CFBundleShortVersionString -string "$marketing_version" \
        "${project_directory}"/"${project}"/Info.plist
    plutil -replace CFBundleVersion -string "$build_version" \
        "${project_directory}"/"${project}"/Info.plist
}

project_directory="$(full_path_of_directory xcode-github)"
cd "$project_directory"

build_products_directory="$project_directory"/Products
rm -Rf "$build_products_directory"
mkdir -p "$build_products_directory"

# PROJECT_TEMP_DIR          - Intermediate build files.
# CONFIGURATION_BUILD_DIR   - Built related files.
# BUILT_PRODUCTS_DIR        - Deployed build products.

function build_project() {
    local project="$1"
    local executable="$2"
    printf "${textBold}>>> Building '$project'...${textNormal}\n" 1>&2
    update_version "$project"
    xcodebuild \
        -project "${project}".xcodeproj \
        -scheme "${project}" \
        -configuration Release \
        -quiet clean build \
        CONFIGURATION_BUILD_DIR="$build_products_directory"
    codesign -dv --verbose=4 "$build_products_directory"/"$executable"
    echo ""
}

function compress_product() {
    local product="$build_products_directory"/"$1"
    ditto -c -k --sequesterRsrc --keepParent "$product" "$product".zip
    rm -rf "$product"
}

build_project XcodeGitHub       XcodeGitHub.framework/Versions/A/XcodeGitHub
build_project xcode-github-cli  xcode-github
build_project xcode-github-app  XcodeGitHub.app

compress_product xcode-github.dSYM
compress_product XcodeGitHub.app
compress_product XcodeGitHub.app.dSYM
compress_product XcodeGitHub.framework

rm -Rf "$build_products_directory"/libXcodeGitHub.a
rm -Rf "$build_products_directory"/usr

printf "${textBold}>>> Build ${marketing_version}(${build_version}) products in 'Products':${textNormal}\n"
ls -al "$build_products_directory"

if ! askYN "Release version ${marketing_version}?"
then
    exit 1
fi

git add --all
git commit --allow-empty -m "Release ${marketing_version}."
git tag v"${marketing_version}"
git_branch=$(git symbolic-ref --short HEAD)
git push --tags origin "$git_branch"
